1.7.0

In [2]:
import yfinance as yf
import pandas as pd
from datetime import datetime
from dateutil.relativedelta import relativedelta

In [27]:
ticker = "TCS.NS"

In [3]:

end_date = datetime.today()
start_date = end_date - relativedelta(years=5)
print("Start Date:", start_date.date())
print("End Date:", end_date.date())

data = yf.download(
    ticker,
    start=start_date,
    end=end_date,
    interval="1d",
    auto_adjust=False
)

Start Date: 2021-09-03
End Date: 2026-09-03

[*********************100%***********************]  1 of 1 completed

In [4]:
data = data.reset_index()
print(data.head())

Price        Date    Adj Close        Close         High          Low  \
Ticker                  TCS.NS       TCS.NS       TCS.NS       TCS.NS
0      2021-09-03  3337.582764  3842.050049  3856.899902  3804.550049
1      2021-09-06  3346.226318  3852.000000  3877.600098  3814.000000
2      2021-09-07  3314.866455  3815.899902  3869.949951  3808.250000
3      2021-09-08  3278.598389  3774.149902  3815.000000  3756.000000
4      2021-09-09  3293.583252  3791.399902  3808.699951  3765.000000

Price          Open   Volume
Ticker       TCS.NS   TCS.NS
0       3825.000000  1746812
1       3849.699951  1723693
2       3864.000000  1585039
3       3810.000000  4147175
4       3789.699951  1441148

In [5]:
# Save as CSV
data.to_csv("stock_data.csv", index=False)
print("Data saved successfully to stock_data.csv")

Data saved successfully to stock_data.csv

In [6]:
df=pd.read_csv(r"stock_data.csv")

In [12]:
df.info()
print(df.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1241 entries, 0 to 1240
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1240 non-null   object
 1   Adj Close  1241 non-null   object
 2   Close      1241 non-null   object
 3   High       1241 non-null   object
 4   Low        1241 non-null   object
 5   Open       1241 non-null   object
 6   Volume     1241 non-null   object
dtypes: object(7)
memory usage: 68.0+ KB
Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [13]:
df.isna().sum()

Date         1
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [15]:
df=df.iloc[1:].reset_index(drop=True)
df.head()

,Date,Adj Close,Close,High,Low,Open,Volume
0,2021-09-06,3346.226318359375,3852.0,3877.60009765625,3814.0,3849.699951171875,1723693
1,2021-09-07,3314.866455078125,3815.89990234375,3869.949951171875,3808.25,3864.0,1585039
2,2021-09-08,3278.598388671875,3774.14990234375,3815.0,3756.0,3810.0,4147175
3,2021-09-09,3293.583251953125,3791.39990234375,3808.699951171875,3765.0,3789.699951171875,1441148
4,2021-09-13,3340.449462890625,3845.35009765625,3852.39990234375,3767.0,3767.0,1691473

In [16]:
df=df.dropna()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1239 entries, 0 to 1238
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1239 non-null   object
 1   Adj Close  1239 non-null   object
 2   Close      1239 non-null   object
 3   High       1239 non-null   object
 4   Low        1239 non-null   object
 5   Open       1239 non-null   object
 6   Volume     1239 non-null   object
dtypes: object(7)
memory usage: 67.9+ KB

In [20]:
x=df["Date"].duplicated().sum()
print(x)
if x>0:
    df = df.drop_duplicates(subset=["Date"])

0

In [21]:
# Conversions
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
price_columns = ["Open", "High", "Low", "Close", "Adj Close"]
for col in price_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")
df["Volume"] = pd.to_numeric(df["Volume"], errors="coerce")

In [25]:
for col in price_columns:
    df[col] = df[col].round(2)

df = df.sort_values("Date").reset_index(drop=True)

df.head()

        Date  Adj Close    Close     High      Low    Open   Volume
0 2021-09-06    3346.23  3852.00  3877.60  3814.00  3849.7  1723693
1 2021-09-07    3314.87  3815.90  3869.95  3808.25  3864.0  1585039
2 2021-09-08    3278.60  3774.15  3815.00  3756.00  3810.0  4147175
3 2021-09-09    3293.58  3791.40  3808.70  3765.00  3789.7  1441148
4 2021-09-13    3340.45  3845.35  3852.40  3767.00  3767.0  1691473

In [26]:
df.to_csv("clean_data.csv", index=False)